# Generated by Django 4.1.6 on 2023-02-14 19:08

import api.validators
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/', validators=[api.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='tier',
            name='thumbnail_size',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(help_text='Thumbnail sizes list'), size=None),
        ),
    ]
