# Generated by Django 4.1.6 on 2023-02-16 11:56

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tier_thumbnail_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=200, upload_to='images/', validators=[api.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='images/'),
        ),
    ]
